<?php
declare(strict_types=1);

/** Arayüz sözlüğü: butonlar, form etiketleri, sabit başlıklar. İçerik metinleri DB'dedir. */
function sozluk(): array
{
    return [
        'tr' => [
            'nav_anasayfa' => 'Ana Sayfa', 'nav_menu' => 'Lezzetlerimiz', 'nav_hakkimizda' => 'Hakkımızda',
            'nav_franchise' => 'Franchise', 'nav_iletisim' => 'İletişim', 'nav_siparis' => 'Sipariş Ver',
            'btn_menu' => 'Menüyü keşfet', 'btn_franchise_ol' => 'Franchise', 'btn_hikaye' => 'Hikayemizi okuyun',
            'btn_basvuru_formu' => 'Başvuru formu →', 'btn_basvur_gonder' => 'Başvuruyu gönder',
            'btn_mesaj_gonder' => 'Mesajı gönder', 'btn_hemen_basvur' => 'Hemen başvur', 'incele' => 'İncele →',
            'frm_ad' => 'Ad', 'frm_soyad' => 'Soyad', 'frm_telefon' => 'Telefon', 'frm_eposta' => 'E-posta',
            'frm_sehir' => 'Yatırım Yapmak İstediğiniz Şehir/Semt', 'frm_dusunce' => 'Düşüncelerinizi Bizimle Paylaşın',
            'frm_adiniz' => 'Adınız', 'frm_konu' => 'Konu', 'frm_mesajiniz' => 'Mesajınız',
            'basvuru_formu' => 'Başvuru formu', 'mesaj_gonderin' => 'Mesaj gönderin',
            'franchise_basvurusu' => 'Franchise başvurusu', 'neden_mantarhane' => 'Neden Mantarhane?',
            'iletisim' => 'İletişim', 'adres_baslik' => 'Restoran adresimiz', 'saat_baslik' => 'Çalışma saatleri',
            'eposta_baslik' => 'E-posta adreslerimiz', 'harita_ac' => 'Haritada aç →',
            'eposta_genel' => 'Genel iletişim', 'eposta_sosyal' => 'Sosyal medya & basın', 'eposta_franchise' => 'Franchise & yatırım',
            'footer_menu' => 'Menü', 'footer_iletisim' => 'İletişim', 'footer_franchise' => 'Franchise',
            'wa_yaz' => 'WhatsApp’tan yazın', 'wa_balon' => 'Sipariş ve bilgi için bize WhatsApp’tan yazın', 'kapat' => 'Kapat',
            'wa_mesaj' => 'Merhaba Mantarhane, bilgi almak istiyorum.',
            'istat_et' => 'hayvansal et', 'istat_kategori' => 'kategori', 'istat_ilk' => 'Türkiye’de ilk',
            'yakinda' => 'Bu kategorinin ürünleri çok yakında burada.',
            'taze_mantar' => 'taze istiridye mantarı', 'basvuru_notu' => 'Başvurunuz doğrudan %s adresine iletilir.',
            'flash_basvuru' => 'Başvurunuz alındı! Franchise ekibimiz en kısa sürede sizinle iletişime geçecek. 🍄',
            'flash_mesaj' => 'Mesajınız alındı! En kısa sürede dönüş yapacağız. 🍄',
            'err_oturum' => 'Oturum doğrulaması başarısız oldu, lütfen tekrar deneyin.',
            'err_hiz' => 'Çok fazla deneme yaptınız. Lütfen bir süre sonra tekrar deneyin.',
            'err_adsoyad' => 'Ad ve soyad zorunludur.', 'err_telefon' => 'Telefon numarası zorunludur.',
            'err_eposta' => 'Geçerli bir e-posta adresi girin.', 'err_sehir' => 'Şehir/semt alanı zorunludur.',
            'err_ad' => 'Adınızı yazın.', 'err_mesaj' => 'Mesajınızı yazın.',
            'err_sistem' => 'Sistemde geçici bir sorun var, lütfen daha sonra tekrar deneyin.',
            'err_kayit' => 'Kaydedilemedi, lütfen daha sonra tekrar deneyin.',
        ],
        'en' => [
            'nav_anasayfa' => 'Home', 'nav_menu' => 'Menu', 'nav_hakkimizda' => 'About',
            'nav_franchise' => 'Franchise', 'nav_iletisim' => 'Contact', 'nav_siparis' => 'Order Now',
            'btn_menu' => 'Explore the menu', 'btn_franchise_ol' => 'Franchise', 'btn_hikaye' => 'Read our story',
            'btn_basvuru_formu' => 'Application form →', 'btn_basvur_gonder' => 'Submit application',
            'btn_mesaj_gonder' => 'Send message', 'btn_hemen_basvur' => 'Apply now', 'incele' => 'Explore →',
            'frm_ad' => 'First name', 'frm_soyad' => 'Last name', 'frm_telefon' => 'Phone', 'frm_eposta' => 'Email',
            'frm_sehir' => 'City/District You Want to Invest In', 'frm_dusunce' => 'Share Your Thoughts With Us',
            'frm_adiniz' => 'Your name', 'frm_konu' => 'Subject', 'frm_mesajiniz' => 'Your message',
            'basvuru_formu' => 'Application form', 'mesaj_gonderin' => 'Send a message',
            'franchise_basvurusu' => 'Franchise application', 'neden_mantarhane' => 'Why Mantarhane?',
            'iletisim' => 'Contact', 'adres_baslik' => 'Our address', 'saat_baslik' => 'Opening hours',
            'eposta_baslik' => 'Email addresses', 'harita_ac' => 'Open in Maps →',
            'eposta_genel' => 'General', 'eposta_sosyal' => 'Social media & press', 'eposta_franchise' => 'Franchise & investment',
            'footer_menu' => 'Menu', 'footer_iletisim' => 'Contact', 'footer_franchise' => 'Franchise',
            'wa_yaz' => 'Message us on WhatsApp', 'wa_balon' => 'Orders or questions? Message us on WhatsApp', 'kapat' => 'Close',
            'wa_mesaj' => 'Hello Mantarhane, I would like some information.',
            'istat_et' => 'animal meat', 'istat_kategori' => 'categories', 'istat_ilk' => 'first in Türkiye',
            'yakinda' => 'Products in this category are coming soon.',
            'taze_mantar' => 'fresh oyster mushroom', 'basvuru_notu' => 'Your application goes directly to %s.',
            'flash_basvuru' => 'Application received! Our franchise team will contact you shortly. 🍄',
            'flash_mesaj' => 'Message received! We will get back to you soon. 🍄',
            'err_oturum' => 'Session verification failed, please try again.',
            'err_hiz' => 'Too many attempts. Please try again later.',
            'err_adsoyad' => 'First and last name are required.', 'err_telefon' => 'Phone number is required.',
            'err_eposta' => 'Enter a valid email address.', 'err_sehir' => 'City/district is required.',
            'err_ad' => 'Enter your name.', 'err_mesaj' => 'Enter your message.',
            'err_sistem' => 'A temporary issue occurred, please try again later.',
            'err_kayit' => 'Could not be saved, please try again later.',
        ],
        'ar' => [
            'nav_anasayfa' => 'الرئيسية', 'nav_menu' => 'القائمة', 'nav_hakkimizda' => 'من نحن',
            'nav_franchise' => 'فرنشايز', 'nav_iletisim' => 'اتصل بنا', 'nav_siparis' => 'اطلب الآن',
            'btn_menu' => 'استكشف القائمة', 'btn_franchise_ol' => 'فرنشايز', 'btn_hikaye' => 'اقرأ قصتنا',
            'btn_basvuru_formu' => 'نموذج الطلب ←', 'btn_basvur_gonder' => 'إرسال الطلب',
            'btn_mesaj_gonder' => 'إرسال الرسالة', 'btn_hemen_basvur' => 'قدّم الآن', 'incele' => 'استكشف ←',
            'frm_ad' => 'الاسم', 'frm_soyad' => 'اللقب', 'frm_telefon' => 'الهاتف', 'frm_eposta' => 'البريد الإلكتروني',
            'frm_sehir' => 'المدينة/الحي الذي تريد الاستثمار فيه', 'frm_dusunce' => 'شاركنا أفكارك',
            'frm_adiniz' => 'اسمك', 'frm_konu' => 'الموضوع', 'frm_mesajiniz' => 'رسالتك',
            'basvuru_formu' => 'نموذج الطلب', 'mesaj_gonderin' => 'أرسل رسالة',
            'franchise_basvurusu' => 'طلب فرنشايز', 'neden_mantarhane' => 'لماذا مانتارهانة؟',
            'iletisim' => 'اتصل بنا', 'adres_baslik' => 'عنوان المطعم', 'saat_baslik' => 'ساعات العمل',
            'eposta_baslik' => 'عناوين البريد الإلكتروني', 'harita_ac' => 'افتح في الخرائط ←',
            'eposta_genel' => 'التواصل العام', 'eposta_sosyal' => 'الإعلام والصحافة', 'eposta_franchise' => 'الفرنشايز والاستثمار',
            'footer_menu' => 'القائمة', 'footer_iletisim' => 'اتصل بنا', 'footer_franchise' => 'فرنشايز',
            'wa_yaz' => 'راسلنا عبر واتساب', 'wa_balon' => 'للطلبات والاستفسارات راسلنا عبر واتساب', 'kapat' => 'إغلاق',
            'wa_mesaj' => 'مرحباً مانتارهانه، أود الحصول على بعض المعلومات.',
            'istat_et' => 'لحوم', 'istat_kategori' => 'أصناف', 'istat_ilk' => 'الأول في تركيا',
            'yakinda' => 'منتجات هذا الصنف قريبًا هنا.',
            'taze_mantar' => 'فطر محار طازج', 'basvuru_notu' => 'يصل طلبك مباشرة إلى %s.',
            'flash_basvuru' => 'تم استلام طلبك! سيتواصل معك فريق الفرنشايز قريبًا. 🍄',
            'flash_mesaj' => 'تم استلام رسالتك! سنعود إليك قريبًا. 🍄',
            'err_oturum' => 'فشل التحقق من الجلسة، حاول مرة أخرى.',
            'err_hiz' => 'محاولات كثيرة جدًا. حاول لاحقًا.',
            'err_adsoyad' => 'الاسم واللقب مطلوبان.', 'err_telefon' => 'رقم الهاتف مطلوب.',
            'err_eposta' => 'أدخل بريدًا إلكترونيًا صالحًا.', 'err_sehir' => 'حقل المدينة/الحي مطلوب.',
            'err_ad' => 'اكتب اسمك.', 'err_mesaj' => 'اكتب رسالتك.',
            'err_sistem' => 'حدثت مشكلة مؤقتة، حاول لاحقًا.',
            'err_kayit' => 'تعذر الحفظ، حاول لاحقًا.',
        ],
        'ru' => [
            'nav_anasayfa' => 'Главная', 'nav_menu' => 'Меню', 'nav_hakkimizda' => 'О нас',
            'nav_franchise' => 'Франшиза', 'nav_iletisim' => 'Контакты', 'nav_siparis' => 'Заказать',
            'btn_menu' => 'Открыть меню', 'btn_franchise_ol' => 'Франшиза', 'btn_hikaye' => 'Наша история',
            'btn_basvuru_formu' => 'Форма заявки →', 'btn_basvur_gonder' => 'Отправить заявку',
            'btn_mesaj_gonder' => 'Отправить сообщение', 'btn_hemen_basvur' => 'Подать заявку', 'incele' => 'Смотреть →',
            'frm_ad' => 'Имя', 'frm_soyad' => 'Фамилия', 'frm_telefon' => 'Телефон', 'frm_eposta' => 'Email',
            'frm_sehir' => 'Город/район для инвестиций', 'frm_dusunce' => 'Поделитесь своими мыслями',
            'frm_adiniz' => 'Ваше имя', 'frm_konu' => 'Тема', 'frm_mesajiniz' => 'Ваше сообщение',
            'basvuru_formu' => 'Форма заявки', 'mesaj_gonderin' => 'Написать нам',
            'franchise_basvurusu' => 'Заявка на франшизу', 'neden_mantarhane' => 'Почему Mantarhane?',
            'iletisim' => 'Контакты', 'adres_baslik' => 'Адрес ресторана', 'saat_baslik' => 'Часы работы',
            'eposta_baslik' => 'Электронная почта', 'harita_ac' => 'Открыть на карте →',
            'eposta_genel' => 'Общие вопросы', 'eposta_sosyal' => 'Соцсети и пресса', 'eposta_franchise' => 'Франшиза и инвестиции',
            'footer_menu' => 'Меню', 'footer_iletisim' => 'Контакты', 'footer_franchise' => 'Франшиза',
            'wa_yaz' => 'Напишите нам в WhatsApp', 'wa_balon' => 'Заказы и вопросы — пишите нам в WhatsApp', 'kapat' => 'Закрыть',
            'wa_mesaj' => 'Здравствуйте, Mantarhane! Хочу узнать подробнее.',
            'istat_et' => 'мяса', 'istat_kategori' => 'категорий', 'istat_ilk' => 'первые в Турции',
            'yakinda' => 'Товары этой категории скоро появятся.',
            'taze_mantar' => 'свежие вешенки', 'basvuru_notu' => 'Ваша заявка отправляется напрямую на %s.',
            'flash_basvuru' => 'Заявка получена! Наша команда свяжется с вами в ближайшее время. 🍄',
            'flash_mesaj' => 'Сообщение получено! Мы скоро ответим. 🍄',
            'err_oturum' => 'Ошибка проверки сессии, попробуйте ещё раз.',
            'err_hiz' => 'Слишком много попыток. Попробуйте позже.',
            'err_adsoyad' => 'Имя и фамилия обязательны.', 'err_telefon' => 'Укажите номер телефона.',
            'err_eposta' => 'Введите корректный email.', 'err_sehir' => 'Укажите город/район.',
            'err_ad' => 'Введите ваше имя.', 'err_mesaj' => 'Введите сообщение.',
            'err_sistem' => 'Временная неполадка, попробуйте позже.',
            'err_kayit' => 'Не удалось сохранить, попробуйте позже.',
        ],
        'de' => [
            'nav_anasayfa' => 'Start', 'nav_menu' => 'Karte', 'nav_hakkimizda' => 'Über uns',
            'nav_franchise' => 'Franchise', 'nav_iletisim' => 'Kontakt', 'nav_siparis' => 'Bestellen',
            'btn_menu' => 'Karte entdecken', 'btn_franchise_ol' => 'Franchise', 'btn_hikaye' => 'Unsere Geschichte',
            'btn_basvuru_formu' => 'Bewerbungsformular →', 'btn_basvur_gonder' => 'Bewerbung senden',
            'btn_mesaj_gonder' => 'Nachricht senden', 'btn_hemen_basvur' => 'Jetzt bewerben', 'incele' => 'Entdecken →',
            'frm_ad' => 'Vorname', 'frm_soyad' => 'Nachname', 'frm_telefon' => 'Telefon', 'frm_eposta' => 'E-Mail',
            'frm_sehir' => 'Stadt/Bezirk für Ihre Investition', 'frm_dusunce' => 'Teilen Sie Ihre Gedanken mit uns',
            'frm_adiniz' => 'Ihr Name', 'frm_konu' => 'Betreff', 'frm_mesajiniz' => 'Ihre Nachricht',
            'basvuru_formu' => 'Bewerbungsformular', 'mesaj_gonderin' => 'Nachricht senden',
            'franchise_basvurusu' => 'Franchise-Bewerbung', 'neden_mantarhane' => 'Warum Mantarhane?',
            'iletisim' => 'Kontakt', 'adres_baslik' => 'Unsere Adresse', 'saat_baslik' => 'Öffnungszeiten',
            'eposta_baslik' => 'E-Mail-Adressen', 'harita_ac' => 'In Karten öffnen →',
            'eposta_genel' => 'Allgemein', 'eposta_sosyal' => 'Social Media & Presse', 'eposta_franchise' => 'Franchise & Investment',
            'footer_menu' => 'Karte', 'footer_iletisim' => 'Kontakt', 'footer_franchise' => 'Franchise',
            'wa_yaz' => 'Schreiben Sie uns auf WhatsApp', 'wa_balon' => 'Bestellung oder Frage? Schreiben Sie uns auf WhatsApp', 'kapat' => 'Schließen',
            'wa_mesaj' => 'Hallo Mantarhane, ich hätte gerne ein paar Informationen.',
            'istat_et' => 'Fleisch', 'istat_kategori' => 'Kategorien', 'istat_ilk' => 'Erste der Türkei',
            'yakinda' => 'Produkte dieser Kategorie folgen in Kürze.',
            'taze_mantar' => 'frische Austernpilze', 'basvuru_notu' => 'Ihre Bewerbung geht direkt an %s.',
            'flash_basvuru' => 'Bewerbung erhalten! Unser Franchise-Team meldet sich in Kürze. 🍄',
            'flash_mesaj' => 'Nachricht erhalten! Wir melden uns bald. 🍄',
            'err_oturum' => 'Sitzungsprüfung fehlgeschlagen, bitte erneut versuchen.',
            'err_hiz' => 'Zu viele Versuche. Bitte später erneut versuchen.',
            'err_adsoyad' => 'Vor- und Nachname sind erforderlich.', 'err_telefon' => 'Telefonnummer ist erforderlich.',
            'err_eposta' => 'Geben Sie eine gültige E-Mail-Adresse ein.', 'err_sehir' => 'Stadt/Bezirk ist erforderlich.',
            'err_ad' => 'Geben Sie Ihren Namen ein.', 'err_mesaj' => 'Geben Sie Ihre Nachricht ein.',
            'err_sistem' => 'Vorübergehendes Problem, bitte später erneut versuchen.',
            'err_kayit' => 'Konnte nicht gespeichert werden, bitte später erneut versuchen.',
        ],
    ];
}
